[phases.setup]
nixPkgs = ['python311', 'postgresql']

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:${PORT:-8000}"

[deploy]
startCommand = "python init_db.py && gunicorn main:app --bind 0.0.0.0:${PORT:-8000} --workers 4 --timeout 120 --keep-alive 5 --log-level info"

[build]
predictCmds = false

[variables]
PYTHONUNBUFFERED = "1"