# nixpacks.toml

[build]
packages = ["ffmpeg"]

[build.phases.install]
commands = [
  "echo 'Установка зависимостей...'",
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[build.phases.build]
commands = [
  "echo 'Инициализация базы данных...'",
  "python init_db.py",
  "ffmpeg -version"  # Проверка установки ffmpeg
]

[run]
command = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 4"

[run.processes]
web = 1

[phases.setup.environment]
DATABASE_URL = { value = "${DATABASE_URL}" }
FLASK_ENV = { value = "production" }
PYTHONPATH = { value = "." }
