# nixpacks.toml - Configuration for Coolify deployment

[phases.setup]
nixPkgs = [
    "ffmpeg",
    "python311",
    "pkg-config",
    "postgresql",
    "python311Packages.pip"  # Добавлено для установки pip
]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt",
    "python3 -m pip install python-dotenv gunicorn"
]

[phases.build]
cmds = [
    "mkdir -p downloads",
    "chmod 755 downloads",
    "python3 init_db.py"
]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:${PORT:-8000} --workers 4 --timeout 120 --keep-alive 5 --log-level info"

[phases.setup.environment]
DATABASE_URL = { value = "${DATABASE_URL}" }
FLASK_ENV = { value = "production" }
PYTHONPATH = { value = "." }
NIXPACKS_PATH = { value = "/opt/venv/bin:/usr/local/bin" }  # Определение NIXPACKS_PATH

[start.environment]
SOURCE_DATE_EPOCH = "315532800"
FLASK_APP = "app"
