# nixpacks.toml

[shell]
file = "default.nix"

[build]
phases = {
  install = [
    "echo 'Установка зависимостей...'",
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
  ]
  build = [
    "echo 'Сборка приложения...'",
    "python init_db.py",
    "ffmpeg -version"
  ]
}

[run]
command = "gunicorn app.main:app --bind 0.0.0.0:$PORT --workers 4"

[run.processes]
web = 1
