[phases.setup]
nixPkgs = ['python311', 'postgresql', 'ffmpeg', 'netcat-gnu']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements.txt']

[start]
cmd = 'chmod +x start.sh && ./start.sh'