[phases.setup]
nixPkgs = [
    "python311",
    "gcc",
    "postgresql",
    "ffmpeg",
    "pkg-config"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "mkdir -p downloads",
    "chmod 755 downloads"
]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:${PORT:-3333} --workers 4 --timeout 120 --keep-alive 5 --log-level info"

[variables]
FLASK_ENV = "production"
FLASK_APP = "app"
SOURCE_DATE_EPOCH = "315532800" 